# Standard
- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"
- name: "stale"
  color: "ffffff"
  description: "PR or issue has sat without activity too long and has become stale. Will be closed 7 days from the day it is marked stale."
- name: "¯\_(ツ)_/¯"
  color: "ffffff"
  description: "No description necessary."
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"
- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"
- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"
- name: "invalid"
  color: "e4e669"
  description: "Invalid issue/PR and will be closed."
- name: "good-to-merge"
  color: "e4e669"
  description: "PR is good to merge when checks pass."


# Issue/PR types
- name: "type: feat"
  color: "fbca04"
- name: "type: bug"
  color: "fbca04"
- name: "type: discussion"
  color: "fbca04"
- name: "type: rfc"
  color: "fbca04"
- name: "type: follow-up"
  color: "fbca04"
- name: "type: research"
  color: "fbca04"

# Triage
- name: "triage: ok"
  color: "fef2c0"
  description: "Indicates an issue is sufficient to be worked and will be prioritized."
- name: "triage: duplicate"
  color: "fef2c0"
  description: "Indicates an issue is a duplicate of an already open issue."
- name: "triage: needs-information"
  color: "fef2c0"
  description: "Indicates an issue needs more information in order to work on it."
- name: "triage: not-reproducible"
  color: "fef2c0"
  description: "Indicates an issue can no be reproduced as described."

# Relates to a configuration/schema specification
- name: "svc: schema/launch"
  color: "0e52cc"

# Relates to a public package
- name: "svc: pkg/spec"
  color: "0e52cc"

# Core/Internal Packages
- name: "svc: core"
  color: "0e52cc"
- name: "svc: core/api"
  color: "0e52cc"
- name: "svc: core/event"
  color: "0e52cc"
- name: "svc: core/db"
  color: "0e52cc"
- name: "svc: cli"
  color: "0e52cc"
- name: "svc: cli/project"
  color: "0e52cc"


# Blockers
- name: "do-not-merge"
  color: "e11d21"
  description: "Do NOT merge this PR."
- name: "do-not-merge: hold"
  color: "e11d21"
  description: "PR was placed on hold by a maintainer and will not be merged until it is no longer held."
- name: "do-not-merge: work-in-progress"
  color: "e11d21"
  description: "PR is a work-in-progress and will not be merged."
- name: "do-not-merge: bad-commit-message"
  color: "e11d21"
  description: "PR contains a bad commit message and will not be merged until corrected."
- name: "do-not-merge: missing-tests"
  color: "e11d21"
  description: "PR contains code that is missig automated tests and will not be merged until tests compliment the PR."
- name: "do-not-merge: manual-testing-needed"
  color: "e11d21"
  description: "PR contains changes that must be manually tested, don't merge until it's been marked as approved."
- name: "do-not-merge: missing-docs"
  color: "e11d21"
  description: "PR contains changes that must be documented, don't merge until docs are updated."

# Information for Maintainers
- name: "release-notes"
  color: "c2e0c6"
  description: "Denotes a PR that should be considered when creating release notes."
- name: "release-notes: ignore"
  color: "c2e0c6"
  description: "Denotes a PR that does not warrant mention in release notes."
- name: "release-notes: action-required"
  color: "c2e0c6"
  description: "Denotes a PR that introduces potentially breaking changes and should state such in the release notes."

# Priorities
- name: "priority: low"
  color: "009800"
- name: "priority: medium"
  color: "fbca04"
- name: "priority: high"
  color: "eb6420"
- name: "priority: critical"
  color: "e11d21"