on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
name: Analysis
jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Go Test w/ Coverage
        run: go test "./..." -coverprofile="coverage.out" -covermode=count -json > report.json
      - name: Go Vet w/ Report
        run: go vet -json "./..." > vet-report.json
      - name: Perform Linting w/ Report
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.33.0
          /home/runner/go/bin/golangci-lint run ./... --verbose --issues-exit-code 0 --out-format checkstyle > golangci-lint.out
      - name: SonarCloud Analysis
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
